/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Social Learning Platform API
 * The Social Learning Platform API description
 * OpenAPI spec version: 1.0
 */
import type { BodyUpdateMetaUserTypeLevel } from './bodyUpdateMetaUserTypeLevel';

export interface BodyUpdateMetaUser {
  /** @nullable */
  topicsId?: string | null;
  level: number;
  typeLevel: BodyUpdateMetaUserTypeLevel;
}
