/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Social Learning Platform API
 * The Social Learning Platform API description
 * OpenAPI spec version: 1.0
 */

export type BodyUpdateMetaUserTypeLevel = typeof BodyUpdateMetaUserTypeLevel[keyof typeof BodyUpdateMetaUserTypeLevel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BodyUpdateMetaUserTypeLevel = {
  toeic: 'toeic',
  ielts: 'ielts',
} as const;
