/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Social Learning Platform API
 * The Social Learning Platform API description
 * OpenAPI spec version: 1.0
 */
import type { MetaDataUsersDtoTypeLevel } from './metaDataUsersDtoTypeLevel';

export interface MetaDataUsersDto {
  userId: string;
  /** @nullable */
  topicsId?: string | null;
  /** @nullable */
  facebookId?: string | null;
  currentTopic: string;
  profile: string;
  level: number;
  typeLevel: MetaDataUsersDtoTypeLevel;
}
