/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Social Learning Platform API
 * The Social Learning Platform API description
 * OpenAPI spec version: 1.0
 */

export type MetaDataUsersDtoTypeLevel = typeof MetaDataUsersDtoTypeLevel[keyof typeof MetaDataUsersDtoTypeLevel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MetaDataUsersDtoTypeLevel = {
  toeic: 'toeic',
  ielts: 'ielts',
} as const;
