/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Social Learning Platform API
 * The Social Learning Platform API description
 * OpenAPI spec version: 1.0
 */

export type PublicUsersDtoRole = typeof PublicUsersDtoRole[keyof typeof PublicUsersDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PublicUsersDtoRole = {
  user: 'user',
  admin: 'admin',
} as const;
