/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Social Learning Platform API
 * The Social Learning Platform API description
 * OpenAPI spec version: 1.0
 */
import type { PublicUsersDtoRole } from './publicUsersDtoRole';

export interface PublicUsersDto {
  id: string;
  email: string;
  name: string;
  role: PublicUsersDtoRole;
}
