/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Social Learning Platform API
 * The Social Learning Platform API description
 * OpenAPI spec version: 1.0
 */
import type { WordItemDto } from './wordItemDto';

export interface ResChatWithGeminiDto {
  fixed: string;
  list: WordItemDto[];
  explain: string;
  reply: string;
  vi: string;
}
