/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Social Learning Platform API
 * The Social Learning Platform API description
 * OpenAPI spec version: 1.0
 */
import type { VocabulariesDto } from './vocabulariesDto';

export interface ResFindOneTopicDto {
  id: string;
  name: string;
  /** @nullable */
  description?: string | null;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  deletedAt?: string | null;
  vocabularies: VocabulariesDto[];
}
