/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Social Learning Platform API
 * The Social Learning Platform API description
 * OpenAPI spec version: 1.0
 */

export interface SuggestedVocabularyDto {
  /** An English word or phrase */
  word: string;
  /** Phonetic transcription of the word */
  phonetic?: string;
  /** Example sentence using the word */
  example?: string;
  /** Vietnamese meaning of the word or phrase */
  meaning: string;
  /** Example sentence using the word in Vietnamese */
  meaningExample?: string;
}
