/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Social Learning Platform API
 * The Social Learning Platform API description
 * OpenAPI spec version: 1.0
 */

export interface TransactionHistoryDto {
  id: string;
  userId: string;
  amount: number;
  currency: string;
  /** @nullable */
  description?: string | null;
  createdAt: string;
}
