/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Social Learning Platform API
 * The Social Learning Platform API description
 * OpenAPI spec version: 1.0
 */

export interface VocabulariesDto {
  id: string;
  topicId: string;
  context: string;
  meaning: string;
  phonetic: string;
  example: string;
  meaningExample: string;
  studyCount: number;
  createdAt: string;
  learnedAt: string;
}
